/**
 * Pinned OFFICIAL TEXT-warp geometry catalog (ECMA-376 Part 1, 5th edition, December 2016).
 *
 * Source: ECMA-376-1_5th_edition_december_2016.zip > OfficeOpenXML-DrawingMLGeometries.zip
 *         > presetTextWarpDefinitions.xml
 * Source SHA-256 (bytes): 89640bd4aeedfa2c578d1d1acc50d569865ebdef315fd4b468087c25e36acada
 * Reference: https://ecma-international.org/publications-and-standards/standards/ecma-376/
 *
 * TEXT-warp catalog (a:bodyPr > a:prstTxWarp). Deliberately NOT routed through the shape
 * preset catalog (presets.json): the text-warp path context seeds its own guide set
 * (l,t,r,b,w,h,hc,vc,wd2,hd2,wd3,ss,cd2) per ECMA-376; reusing shape validation would
 * evaluate the wrong seed set.
 *
 * Tokens are preserved verbatim; avLst keeps official DEFAULT FORMULAS (e.g.
 * textArchUp adj = "val cd2"); gdLst keeps derived guide order; ahLst provides the
 * official handle bounds; pathLst keeps command order with guide-reference tokens.
 *
 * Regenerated by scripts/warp/generate-text-warp-catalog.py; regeneration asserts the pinned
 * hash. Generated content is a normalized transcription of the pinned official XML
 * (attribution: ECMA-376).
 */

export interface TextWarpCommand {
  kind: 'moveTo' | 'lnTo' | 'quadBezTo' | 'cubicBezTo' | 'arcTo' | 'close'
  /** Point tokens (guide references or numeric literals), xy interleaved. */
  values?: ReadonlyArray<string | number>
  /** arcTo carries its four tokens as attributes (DrawingML angle units). */
  attrs?: Partial<Record<'wR' | 'hR' | 'stAng' | 'swAng', string | number>>
}

export interface TextWarpDefinition {
  /** avLst: official adjustment DEFAULTS as guide formulas. */
  adjustments: ReadonlyArray<readonly [string, string]>
  /** gdLst: ordered derived guides. */
  guides: ReadonlyArray<readonly [string, string]>
  /** ahLst: official handle (adjustment) bounds. */
  handles: ReadonlyArray<{ guide: string; axis: 'angle' | 'radius' | 'y' | 'x'; min: string | number; max: string | number }>
  /** pathLst: authoritative boundary commands. */
  paths: ReadonlyArray<{ attrs: Partial<Record<'w' | 'h', string | number>>; commands: ReadonlyArray<TextWarpCommand> }>
}

export const OFFICIAL_TEXT_WARP_REFERENCE = {
  file: 'presetTextWarpDefinitions.xml',
  sha256: '89640bd4aeedfa2c578d1d1acc50d569865ebdef315fd4b468087c25e36acada',
  source: 'ECMA-376 Part 1 5th edition (December 2016), DrawingML preset text warp definitions',
} as const

export const TEXT_WARP_CATALOG: Readonly<Record<string, TextWarpDefinition>> = {
  "textArchUp": {
    adjustments: [
      ["adj", "val cd2"],
    ],
    guides: [
      ["adval", "pin 0 adj 21599999"],
      ["v1", "+- 10800000 0 adval"],
      ["v2", "+- 32400000 0 adval"],
      ["end", "?: v1 v1 v2"],
      ["w1", "+- 5400000 0 adval"],
      ["w2", "+- 16200000 0 adval"],
      ["d1", "+- end 0 adval"],
      ["d2", "+- 21600000 d1 0"],
      ["c2", "?: w2 d1 d2"],
      ["c1", "?: v1 d2 c2"],
      ["swAng", "?: w1 d1 c1"],
      ["wt1", "sin wd2 adj"],
      ["ht1", "cos hd2 adj"],
      ["dx1", "cat2 wd2 ht1 wt1"],
      ["dy1", "sat2 hd2 ht1 wt1"],
      ["x1", "+- hc dx1 0"],
      ["y1", "+- vc dy1 0"],
    ],
    handles: [
      { guide: "adj", axis: "angle", min: 0, max: 21599999 },
    ],
    paths: [
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["x1", "y1"] },
        { kind: 'arcTo', attrs: { wR: "wd2", hR: "hd2", stAng: "adval", swAng: "swAng" } },
      ] },
    ],
  },
  "textArchDown": {
    adjustments: [
      ["adj", "val 0"],
    ],
    guides: [
      ["adval", "pin 0 adj 21599999"],
      ["v1", "+- 10800000 0 adval"],
      ["v2", "+- 32400000 0 adval"],
      ["nv1", "+- 0 0 v1"],
      ["stAng", "?: nv1 v2 v1"],
      ["w1", "+- 5400000 0 adval"],
      ["w2", "+- 16200000 0 adval"],
      ["d1", "+- adval 0 stAng"],
      ["d2", "+- d1 0 21600000"],
      ["v3", "+- 0 0 10800000"],
      ["c2", "?: w2 d1 d2"],
      ["c1", "?: v1 d2 c2"],
      ["c0", "?: w1 d1 c1"],
      ["swAng", "?: stAng c0 v3"],
      ["wt1", "sin wd2 adj"],
      ["ht1", "cos hd2 adj"],
      ["dx1", "cat2 wd2 ht1 wt1"],
      ["dy1", "sat2 hd2 ht1 wt1"],
      ["x1", "+- hc dx1 0"],
      ["y1", "+- vc dy1 0"],
      ["wt2", "sin wd2 stAng"],
      ["ht2", "cos hd2 stAng"],
      ["dx2", "cat2 wd2 ht2 wt2"],
      ["dy2", "sat2 hd2 ht2 wt2"],
      ["x2", "+- hc dx2 0"],
      ["y2", "+- vc dy2 0"],
    ],
    handles: [
      { guide: "adj", axis: "angle", min: 0, max: 21599999 },
    ],
    paths: [
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["x2", "y2"] },
        { kind: 'arcTo', attrs: { wR: "wd2", hR: "hd2", stAng: "stAng", swAng: "swAng" } },
      ] },
    ],
  },
  "textCircle": {
    adjustments: [
      ["adj", "val 10800000"],
    ],
    guides: [
      ["adval", "pin 0 adj 21599999"],
      ["d0", "+- adval 0 10800000"],
      ["d1", "+- 10800000 0 adval"],
      ["d2", "+- 21600000 0 adval"],
      ["d3", "?: d1 d1 10799999"],
      ["d4", "?: d0 d2 d3"],
      ["swAng", "*/ d4 2 1"],
      ["wt1", "sin wd2 adj"],
      ["ht1", "cos hd2 adj"],
      ["dx1", "cat2 wd2 ht1 wt1"],
      ["dy1", "sat2 hd2 ht1 wt1"],
      ["x1", "+- hc dx1 0"],
      ["y1", "+- vc dy1 0"],
    ],
    handles: [
      { guide: "adj", axis: "angle", min: 0, max: 21599999 },
    ],
    paths: [
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["x1", "y1"] },
        { kind: 'arcTo', attrs: { wR: "wd2", hR: "hd2", stAng: "adval", swAng: "swAng" } },
      ] },
    ],
  },
  "textWave1": {
    adjustments: [
      ["adj1", "val 12500"],
      ["adj2", "val 0"],
    ],
    guides: [
      ["a1", "pin 0 adj1 20000"],
      ["a2", "pin -10000 adj2 10000"],
      ["y1", "*/ h a1 100000"],
      ["dy2", "*/ y1 10 3"],
      ["y2", "+- y1 0 dy2"],
      ["y3", "+- y1 dy2 0"],
      ["y4", "+- b 0 y1"],
      ["y5", "+- y4 0 dy2"],
      ["y6", "+- y4 dy2 0"],
      ["of", "*/ w a2 100000"],
      ["of2", "*/ w a2 50000"],
      ["x1", "abs of"],
      ["dx2", "?: of2 0 of2"],
      ["x2", "+- l 0 dx2"],
      ["dx5", "?: of2 of2 0"],
      ["x5", "+- r 0 dx5"],
      ["dx3", "+/ dx2 x5 3"],
      ["x3", "+- x2 dx3 0"],
      ["x4", "+/ x3 x5 2"],
      ["x6", "+- l dx5 0"],
      ["x10", "+- r dx2 0"],
      ["x7", "+- x6 dx3 0"],
      ["x8", "+/ x7 x10 2"],
      ["x9", "+- r 0 x1"],
      ["xAdj", "+- hc of 0"],
    ],
    handles: [
      { guide: "adj1", axis: "y", min: 0, max: 20000 },
      { guide: "adj2", axis: "x", min: -10000, max: 10000 },
    ],
    paths: [
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["x2", "y1"] },
        { kind: "cubicBezTo", values: ["x3", "y2", "x4", "y3", "x5", "y1"] },
      ] },
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["x6", "y4"] },
        { kind: "cubicBezTo", values: ["x7", "y5", "x8", "y6", "x10", "y4"] },
      ] },
    ],
  },
  "textWave2": {
    adjustments: [
      ["adj1", "val 12500"],
      ["adj2", "val 0"],
    ],
    guides: [
      ["a1", "pin 0 adj1 20000"],
      ["a2", "pin -10000 adj2 10000"],
      ["y1", "*/ h a1 100000"],
      ["dy2", "*/ y1 10 3"],
      ["y2", "+- y1 0 dy2"],
      ["y3", "+- y1 dy2 0"],
      ["y4", "+- b 0 y1"],
      ["y5", "+- y4 0 dy2"],
      ["y6", "+- y4 dy2 0"],
      ["of", "*/ w a2 100000"],
      ["of2", "*/ w a2 50000"],
      ["x1", "abs of"],
      ["dx2", "?: of2 0 of2"],
      ["x2", "+- l 0 dx2"],
      ["dx5", "?: of2 of2 0"],
      ["x5", "+- r 0 dx5"],
      ["dx3", "+/ dx2 x5 3"],
      ["x3", "+- x2 dx3 0"],
      ["x4", "+/ x3 x5 2"],
      ["x6", "+- l dx5 0"],
      ["x10", "+- r dx2 0"],
      ["x7", "+- x6 dx3 0"],
      ["x8", "+/ x7 x10 2"],
      ["x9", "+- r 0 x1"],
      ["xAdj", "+- hc of 0"],
    ],
    handles: [
      { guide: "adj1", axis: "y", min: 0, max: 20000 },
      { guide: "adj2", axis: "x", min: -10000, max: 10000 },
    ],
    paths: [
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["x2", "y1"] },
        { kind: "cubicBezTo", values: ["x3", "y3", "x4", "y2", "x5", "y1"] },
      ] },
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["x6", "y4"] },
        { kind: "cubicBezTo", values: ["x7", "y6", "x8", "y5", "x10", "y4"] },
      ] },
    ],
  },
  "textInflate": {
    adjustments: [
      ["adj", "val 18750"],
    ],
    guides: [
      ["a", "pin 0 adj 20000"],
      ["dy", "*/ a h 100000"],
      ["gd", "*/ dy 1 3"],
      ["gd0", "+- 0 0 gd"],
      ["gd1", "+- h 0 gd0"],
      ["ty", "+- t dy 0"],
      ["by", "+- b 0 dy"],
      ["y0", "+- t gd0 0"],
      ["y1", "+- t gd1 0"],
      ["x0", "+- l wd3 0"],
      ["x1", "+- r 0 wd3"],
    ],
    handles: [
      { guide: "adj", axis: "y", min: 0, max: 20000 },
    ],
    paths: [
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "ty"] },
        { kind: "cubicBezTo", values: ["x0", "y0", "x1", "y0", "r", "ty"] },
      ] },
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "by"] },
        { kind: "cubicBezTo", values: ["x0", "y1", "x1", "y1", "r", "by"] },
      ] },
    ],
  },
  "textDeflate": {
    adjustments: [
      ["adj", "val 18750"],
    ],
    guides: [
      ["a", "pin 0 adj 37500"],
      ["dy", "*/ a ss 100000"],
      ["gd0", "*/ dy 4 3"],
      ["gd1", "+- h 0 gd0"],
      ["adjY", "+- t dy 0"],
      ["y0", "+- t gd0 0"],
      ["y1", "+- t gd1 0"],
      ["x0", "+- l wd3 0"],
      ["x1", "+- r 0 wd3"],
    ],
    handles: [
      { guide: "adj", axis: "y", min: 0, max: 37500 },
    ],
    paths: [
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "t"] },
        { kind: "cubicBezTo", values: ["x0", "y0", "x1", "y0", "r", "t"] },
      ] },
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "b"] },
        { kind: "cubicBezTo", values: ["x0", "y1", "x1", "y1", "r", "b"] },
      ] },
    ],
  },
  "textSlantUp": {
    adjustments: [
      ["adj", "val 55555"],
    ],
    guides: [
      ["a", "pin 0 adj 71431"],
      ["dy", "*/ a h 100000"],
      ["y1", "+- t dy 0"],
      ["y2", "+- b 0 dy"],
    ],
    handles: [
      { guide: "adj", axis: "y", min: 0, max: 71431 },
    ],
    paths: [
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "y1"] },
        { kind: "lnTo", values: ["r", "t"] },
      ] },
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "b"] },
        { kind: "lnTo", values: ["r", "y2"] },
      ] },
    ],
  },
  "textSlantDown": {
    adjustments: [
      ["adj", "val 44445"],
    ],
    guides: [
      ["a", "pin 28569 adj 100000"],
      ["dy", "*/ a h 100000"],
      ["y1", "+- t dy 0"],
      ["y2", "+- b 0 dy"],
    ],
    handles: [
      { guide: "adj", axis: "y", min: 28569, max: 100000 },
    ],
    paths: [
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "t"] },
        { kind: "lnTo", values: ["r", "y2"] },
      ] },
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "y1"] },
        { kind: "lnTo", values: ["r", "b"] },
      ] },
    ],
  },
  "textCurveUp": {
    adjustments: [
      ["adj", "val 45977"],
    ],
    guides: [
      ["a", "pin 0 adj 56338"],
      ["dy", "*/ a h 100000"],
      ["gd1", "*/ dy 3 4"],
      ["gd2", "*/ dy 5 4"],
      ["gd3", "*/ dy 3 8"],
      ["gd4", "*/ dy 1 8"],
      ["gd5", "+- h 0 gd3"],
      ["gd6", "+- gd4 h 0"],
      ["y0", "+- t dy 0"],
      ["y1", "+- t gd1 0"],
      ["y2", "+- t gd2 0"],
      ["y3", "+- t gd3 0"],
      ["y4", "+- t gd4 0"],
      ["y5", "+- t gd5 0"],
      ["y6", "+- t gd6 0"],
      ["x1", "+- l wd3 0"],
      ["x2", "+- r 0 wd3"],
    ],
    handles: [
      { guide: "adj", axis: "y", min: 0, max: 56338 },
    ],
    paths: [
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "y0"] },
        { kind: "cubicBezTo", values: ["x1", "y2", "x2", "y1", "r", "t"] },
      ] },
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "y5"] },
        { kind: "cubicBezTo", values: ["x1", "y6", "x2", "y6", "r", "y5"] },
      ] },
    ],
  },
  "textCurveDown": {
    adjustments: [
      ["adj", "val 45977"],
    ],
    guides: [
      ["a", "pin 0 adj 56338"],
      ["dy", "*/ a h 100000"],
      ["gd1", "*/ dy 3 4"],
      ["gd2", "*/ dy 5 4"],
      ["gd3", "*/ dy 3 8"],
      ["gd4", "*/ dy 1 8"],
      ["gd5", "+- h 0 gd3"],
      ["gd6", "+- gd4 h 0"],
      ["y0", "+- t dy 0"],
      ["y1", "+- t gd1 0"],
      ["y2", "+- t gd2 0"],
      ["y3", "+- t gd3 0"],
      ["y4", "+- t gd4 0"],
      ["y5", "+- t gd5 0"],
      ["y6", "+- t gd6 0"],
      ["x1", "+- l wd3 0"],
      ["x2", "+- r 0 wd3"],
    ],
    handles: [
      { guide: "adj", axis: "y", min: 0, max: 56338 },
    ],
    paths: [
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "t"] },
        { kind: "cubicBezTo", values: ["x1", "y1", "x2", "y2", "r", "y0"] },
      ] },
      { attrs: {  }, commands: [
        { kind: "moveTo", values: ["l", "y5"] },
        { kind: "cubicBezTo", values: ["x1", "y6", "x2", "y6", "r", "y5"] },
      ] },
    ],
  },
}
